language: php

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - master

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - composer self-update
  - composer clear-cache
  - composer install --require-dev

script:
  - vendor/bin/phpunit -c tests/unit/phpunit-cc.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false