language: php

sudo: false

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - master

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - composer self-update
  - composer clear-cache
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests/unit/

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittests

notifications:
  email: false