<?php
/**
 * Created by PhpStorm.
 * User: Forest
 * Date: 18-Nov-17
 * Time: 17:11
 */

use Forestsoft\Billomat\Customer\Customer;
use PHPUnit\Framework\TestCase;

class CustomerTest extends TestCase
{

    /**
     * @var Customer
     */
    private $_object;

    public function testList()
    {
        $list = $this->_object->list();
        $this->assertGreaterThan(0, count($list));
        $this->assertContainsOnly("\Forestsoft\Billomat\Customer\ICustomer", $list);

    }

    /**
     * @group unit
     */
    public function testCreate()
    {
        $this->_object->setFirstName("Luca");
        $this->_object->setLastName("Benakovic");

        $customer = $this->_object->create();

        $this->assertInstanceOf('\Forestsoft\Billomat\Customer\ICustomer', $customer);
        $this->assertNotNull($customer->getId());

        return $customer;
    }

    /**
     * @depends testCreate
     */
    public function testfind($customer)
    {
        $customer = $this->_object->find($customer->getId());

        $this->assertInstanceOf('Forestsoft\Billomat\Customer\ICustomer', $customer);
        $this->assertEquals("Luca", $customer->getFirstName());
        $this->assertEquals("Benakovic", $customer->getLastName());

        return $customer;
    }

    /**
     * @depends testfind
     * 
     * @group integration
     */
    public function testdelete($customer)
    {
        $this->assertEquals(true, $customer->delete());
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $factory = \Forestsoft\Billomat\Factory\Customer::getInstance();
        $config = \Forestsoft\Billomat\TestHelper::getConfig();
        $factory->setConfig(
            $config['integration']['billomat']
        );
        $this->_object = $factory->create();
    }
}
