<?php
/**
 * Created by PhpStorm.
 * User: sebastian.foerster
 * Date: 13.12.2017
 * Time: 14:37
 */

namespace Forestsoft\Billomat\Test;
use PHPUnit\Framework\TestCase;

abstract class AbstractRepositoryTest extends TestCase
{

    protected $_object;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_object = $this->getObject();
    }

    /**
     * @group unit
     */
    public function testInstanceOfIterator()
    {
        $this->assertInstanceOf('\IteratorAggregate', $this->_object);
    }

    /**
     * @group unit
     */
    public function testInstanceOfRepositoryInterface()
    {
        $this->assertInstanceOf($this->getRepositoryInterface(), $this->_object);
    }

    public function testAdd()
    {
        $item1 = $this->getMockBuilder($this->getItemInterface())->getMock();
        $item2 = $this->getMockBuilder($this->getItemInterface())->getMock();

        $this->_object->add($item1);
        $this->_object->add($item2);

        $this->assertEquals(2, count($this->_object));
    }

    abstract protected function getRepositoryInterface();

    abstract protected function getItemInterface();

    abstract protected function getObject();

}