<?php
/**
 * Created by PhpStorm.
 * User: Forest
 * Date: 19-Nov-17
 * Time: 10:26
 */

namespace Forestsoft\Billomat\Mapper;

use PHPUnit\Framework\TestCase;

class MapperTest extends TestCase
{

    /**
     * @dataProvider dp_sources
     */
    public function testMap($expectedMethod, $property, $value)
    {
        $resource = $this->getMockBuilder("Forestsoft\Billomat\Customer\ICustomer")->getMock();

        $resource->expects($this->once())->method($expectedMethod)->with($value);
        
        $this->_object->map($resource, new \ArrayObject([$property => $value]));


    }

    public function dp_sources() 
    {
      return [
        "FirsName" => ["setFirstName", "first_name", "Sebastian"],
        "Archived" => ["setArchived", "archived", false],
      ];
    } 

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_object = new Mapper();
    }

}
