<?php
/**
 * Created by PhpStorm.
 * User: Forest
 * Date: 18-Nov-17
 * Time: 12:48
 */

namespace Forestsoft\Billomat;

use PHPUnit\Framework\TestCase;

class ResourceTest extends BaseTest
{
    /**
     * @var \Forestsoft\Billomat\Resource
     */
    private $_object;

    public function testImplementsResource()
    {
        $this->assertInstanceOf('Forestsoft\Billomat\IResource', $this->_object);
    }

    public function testHasAClientFactory()
    {
        $this->assertInstanceOf('Forestsoft\Billomat\Factory\IClient', $this->_object->getClientFactory());
    }

    public function testDefaultOptions()
    {
        $method = $this->getMethod($this->_object, "getOptions");

        $expected = [
            "billomat" => [
                "billomatId" => null,
                "apiKey" => null,
            ]
        ];
        $this->assertEquals($expected, $method->invoke($this->_object));
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_object = $this->getMockBuilder('Forestsoft\Billomat\Resource')->getMockForAbstractClass();
    }
}
